### ISSUE TITLE
[悬赏] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by black-fruit** [chatchat-space/Langchain-Chatchat#2365]
设备mps

2023-12-12 20:32:43 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2023-12-12 20:32:43 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

TypeError: 'NoneType' object is not iterable

*解决者领赏！*

**Comment by nanayashiki1215** [comment]
pytorch2.1版本支持mps，另外新手不建议使用Mac设备运行本项目，需要改动的地方很多

**Comment by jasonzou** [comment]
[config        "device": "cuda",](https://github.com/chatchat-space/Langchain-Chatchat/blob/1cbad32b6e2c26d09aa444a638cd5aa3b5ee861c/configs/server_config.py.example#L100C1-L102C1) 要改为mps

**Comment by jasonzou** [comment]
==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6-arm64-arm-64bit.
python版本：3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.33


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Volumes/T7/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-en @ mps
==============================Langchain-Chatchat Configuration==============================


2023-12-13 11:24:52,219 - startup.py[line:650] - INFO: 正在启动服务：
2023-12-13 11:24:52,219 - startup.py[line:651] - INFO: 如需查看 llm_api 日志，请前往 /Users/qzou/workspace/Langchain-Chatchat/logs
2023-12-13 11:24:54 | ERROR | stderr | INFO:     Started server process [90583]
2023-12-13 11:24:54 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-13 11:24:54 | ERROR | stderr | INFO:     Application startup complete.
2023-12-13 11:24:54 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-12-13 11:24:56 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker d808a3b8 ...
Loading checkpoint shards:   0%|                                                                              | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████                                                            | 1/7 [00:03<00:18,  3.11s/it]
Loading checkpoint shards:  29%|████████████████████                                                  | 2/7 [00:06<00:15,  3.02s/it]
Loading checkpoint shards:  43%|██████████████████████████████                                        | 3/7 [00:09<00:12,  3.07s/it]
Loading checkpoint shards:  57%|████████████████████████████████████████                              | 4/7 [00:11<00:08,  2.95s/it]
Loading checkpoint shards:  71%|██████████████████████████████████████████████████                    | 5/7 [00:14<00:05,  2.95s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████          | 6/7 [00:17<00:02,  2.93s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 7/7 [00:19<00:00,  2.47s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 7/7 [00:19<00:00,  2.76s/it]
2023-12-13 11:25:16 | ERROR | stderr |
2023-12-13 11:25:23 | INFO | model_worker | Register to controller
INFO:     Started server process [90728]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)


==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6-arm64-arm-64bit.
python版本：3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.33


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Volumes/T7/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-en @ mps


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2023-12-13 11:25:36,557 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62820 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-13 11:25:36,560 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-13 11:25:37,080 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62820 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-13 11:25:37,082 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62820 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-13 11:25:37,091 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"

**Comment by jasonzou** [comment]
> 如果你认为事情这么简单就解决了，那我就不会发issue了。仅仅只有报错你们可能不知道这个东西有多么神奇，我回去录个视频，包括配置环境以及报错全过程

估计不简单。server_config.py 也要改。我前面发的回复没有讲清楚，但是链接给了。

**Comment by mooornn** [comment]
我也是一样的问题，分开跑都没问题，跑这个就不行

**Comment by jeceldx** [comment]
同样，单独跑也是可行，合并就是不行

**Comment by jeceldx** [comment]
> [config "device": "cuda",](https://github.com/chatchat-space/Langchain-Chatchat/blob/1cbad32b6e2c26d09aa444a638cd5aa3b5ee861c/configs/server_config.py.example#L100C1-L102C1) 要改为mps

是这个问题，多谢

**Comment by CaffeineOddity** [comment]
// model_config.py
EMBEDDING_DEVICE = "auto"  //或者指向mps
LLM_DEVICE = "auto"   //或者指向mps
// server_config.py
  "chatglm3-6b": {  # 使用default中的IP和端口
        "device": "auto",  //或者指向mps
    },

你长大了，要学会看代码 :)

**Comment by fanjin2020** [comment]
我也遇到了这个问题，很神奇。这到底怎么解决，没个具体说法吗？

**Comment by jingkeke** [comment]
我是他的httpx.Client(**kwargs)  proxy 策略在 centos7 上有问题, 去掉 proxies 这块就好了.
```
    kwargs.update(timeout=timeout, proxies=default_proxies)
```
