### ISSUE TITLE
[BUG] 利用VLLM进行推理时，加载模型时OOM

### ISSUE THREAD

**Issue by YangQianli92** [chatchat-space/Langchain-Chatchat#2381]
以下是我的 startup.py 中vllm部分的配置，在V100s-32GB模型上部署baichuan2-13B-chat模型，在加载模型时就出现OOM，是啥原因呢？单独用fschat+vllm部署时，可以正常推理。
```args.tokenizer = args.model_path # 如果tokenizer与model_path不一致在此处添加
            args.tokenizer_mode = 'auto'
            args.trust_remote_code= True
            args.download_dir= None
            args.load_format = 'auto'
            args.dtype = 'float16'
            args.seed = 42
            args.worker_use_ray = False
            args.pipeline_parallel_size = 1
            args.tensor_parallel_size = 1
            args.block_size = 16
            args.swap_space = 4  # GiB
            args.gpu_memory_utilization = 0.90
            args.max_num_batched_tokens = None # 一个批次中的最大令牌（tokens）数量，这个取决于你的显卡和大模型设置，设置太大显存会不够
            args.max_num_seqs = 1
            args.disable_log_stats = False
            args.conv_template = "baichuan2-chat"
            args.limit_worker_concurrency = 5
            args.no_register = False
            args.num_gpus = 1 # vllm worker的切分是tensor并行，这里填写显卡的数量
            args.engine_use_ray = False
            args.disable_log_requests = False```
           
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100S-PCI...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   29C    P0    25W / 250W |      4MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+


2023-12-14 13:50:53 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 272.00 MiB. GPU 0 has a total capacty of 31.75 GiB of which 158.69 MiB is free. Including non-PyTorch memory, this process has 31.59 GiB memory in use. Of the allocated memory 30.46 GiB is allocated by PyTorch, and 13.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by YangQianli92** [comment]
已解决

**Comment by learning123hello** [comment]
遇到了同样的问题，请教下是怎么解决的呢？感谢

**Comment by YangQianli92** [comment]
> 遇到了同样的问题，请教下是怎么解决的呢？感谢

尝试修改 args.gpu_memory_utilization = 0.90 的值，我是0.8，0.85，0.9重复试了一下解决的。
如果无法解决的话，可以考虑使用--worker-use-ray  --tensor_parallel_size 这两个参数，实现并行看看

**Comment by liduang** [comment]
> > 遇到了同样的问题，请教下是怎么解决的呢？感谢
> 
> 尝试修改 args.gpu_memory_utilization = 0.90 的值，我是0.8，0.85，0.9重复试了一下解决的。 如果无法解决的话，可以考虑使用--worker-use-ray --tensor_parallel_size 这两个参数，实现并行看看

具体该怎么改呢

**Comment by YangQianli92** [comment]
> > > 遇到了同样的问题，请教下是怎么解决的呢？感谢
> > 
> > 
> > 尝试修改 args.gpu_memory_utilization = 0.90 的值，我是0.8，0.85，0.9重复试了一下解决的。 如果无法解决的话，可以考虑使用--worker-use-ray --tensor_parallel_size 这两个参数，实现并行看看
> 
> 具体该怎么改呢

在startup.py下，找到这个 args.gpu_memory_utilization = 0.90，需要保证你的GPU显存有90%的空闲，且90%能够满足模型的部署，有时候显卡会被其它服务占用GPU导致没有90%这么多显存，就自己根据LLM推理的实际显存来调整
