### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by oushouyou** [chatchat-space/Langchain-Chatchat#2572]
2024-01-06 12:05:18 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-06 12:05:18 | ERROR | stderr | Traceback (most recent call last):
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-01-06 12:05:18 | ERROR | stderr |     self.run()
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-01-06 12:05:18 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/codes/Langchain-Chatchat/startup.py", line 386, in run_model_worker
2024-01-06 12:05:18 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-06 12:05:18 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/codes/Langchain-Chatchat/startup.py", line 214, in create_model_worker_app
2024-01-06 12:05:18 | ERROR | stderr |     worker = ModelWorker(
2024-01-06 12:05:18 | ERROR | stderr |              ^^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-01-06 12:05:18 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-06 12:05:18 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 337, in load_model
2024-01-06 12:05:18 | ERROR | stderr |     model.to(device)
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2460, in to
2024-01-06 12:05:18 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-01-06 12:05:18 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-01-06 12:05:18 | ERROR | stderr |     return self._apply(convert)
2024-01-06 12:05:18 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-06 12:05:18 | ERROR | stderr |     module._apply(fn)
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-06 12:05:18 | ERROR | stderr |     module._apply(fn)
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-06 12:05:18 | ERROR | stderr |     module._apply(fn)
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-01-06 12:05:18 | ERROR | stderr |     param_applied = fn(param)
2024-01-06 12:05:18 | ERROR | stderr |                     ^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-01-06 12:05:18 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-01-06 12:05:18 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 12:05:18 | ERROR | stderr |   File "/Users/harry.wangxr/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
2024-01-06 12:05:18 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-01-06 12:05:18 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

**Comment by oushouyou** [comment]
必须要在cuda的环境中跑么

**Comment by apple-teng** [comment]
我也遇到这个问题了，等结果。。。

**Comment by apple-teng** [comment]
> 我也遇到这个问题了，等结果。。。

重装cuda和pytorch，问题解决了

**Comment by zolibra** [comment]
toch版本多少？看一下cuda版本，然后看下这个帖子对应一下
https://pytorch.org/get-started/previous-versions/
我也遇到过这个问题，最后是降低了torch版本到2.1.1-cuda11.8

**Comment by lp8608** [comment]
Build cuda_12.3.r12.3
torch==2.1.2
一样报错

**Comment by a442509097** [comment]
我安装个新版的, 然后更新一下streamlit就好了.
```
pip install torch-2.3.0+cu121-cp311-cp311-win_amd64.whl      //网络关系, 使用本地文件安装的方式
pip install torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121

pip install streamlit --upgrade
pip install streamlit-chatbox --upgrade
```
