### ISSUE TITLE
Mac M3，运行报错：AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Jas0nxlee** [chatchat-space/Langchain-Chatchat#2990]
**问题描述 / Problem Description**
Mac M3，运行报错：AssertionError: Torch not compiled with CUDA enabled

==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-14.2.1-arm64-arm-64bit.
python版本：3.11.0 (main, Mar  1 2023, 12:33:14) [Clang 14.0.6 ]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'openai-api'] @ mps
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Users/ljp/Desktop/Langchain-Chatchat/models/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps
==============================Langchain-Chatchat Configuration==============================

2024-02-18 16:11:19,978 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-18 16:11:19,978 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /Users/ljp/Desktop/Langchain-Chatchat/logs
/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-18 16:11:22 | ERROR | stderr | INFO:     Started server process [40994]
2024-02-18 16:11:22 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-18 16:11:22 | ERROR | stderr | INFO:     Application startup complete.
2024-02-18 16:11:22 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-18 16:11:22 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker df183990 ...
Loading checkpoint shards:   0%|                                                    | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████▎                                     | 1/7 [00:00<00:04,  1.34it/s]
Loading checkpoint shards:  29%|████████████▌                               | 2/7 [00:01<00:03,  1.30it/s]
Loading checkpoint shards:  43%|██████████████████▊                         | 3/7 [00:01<00:02,  1.59it/s]
Loading checkpoint shards:  57%|█████████████████████████▏                  | 4/7 [00:02<00:01,  1.62it/s]
Loading checkpoint shards:  71%|███████████████████████████████▍            | 5/7 [00:04<00:02,  1.24s/it]
Loading checkpoint shards:  86%|█████████████████████████████████████▋      | 6/7 [00:07<00:01,  1.62s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████| 7/7 [00:08<00:00,  1.43s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████| 7/7 [00:08<00:00,  1.19s/it]
2024-02-18 16:11:30 | ERROR | stderr |
2024-02-18 16:11:30 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-18 16:11:30 | ERROR | stderr | Traceback (most recent call last):
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-18 16:11:30 | ERROR | stderr |     self.run()
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-18 16:11:30 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/Desktop/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-18 16:11:30 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-18 16:11:30 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/Desktop/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-18 16:11:30 | ERROR | stderr |     worker = ModelWorker(
2024-02-18 16:11:30 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-18 16:11:30 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-18 16:11:30 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-02-18 16:11:30 | ERROR | stderr |     model.to(device)
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
2024-02-18 16:11:30 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-02-18 16:11:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-02-18 16:11:30 | ERROR | stderr |     return self._apply(convert)
2024-02-18 16:11:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-18 16:11:30 | ERROR | stderr |     module._apply(fn)
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-18 16:11:30 | ERROR | stderr |     module._apply(fn)
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-18 16:11:30 | ERROR | stderr |     module._apply(fn)
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-02-18 16:11:30 | ERROR | stderr |     param_applied = fn(param)
2024-02-18 16:11:30 | ERROR | stderr |                     ^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-02-18 16:11:30 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-02-18 16:11:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 16:11:30 | ERROR | stderr |   File "/Users/ljp/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
2024-02-18 16:11:30 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-02-18 16:11:30 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

**Comment by Jas0nxlee** [comment]
已解决。修改configs/server_config.py相关内容
`    "chatglm3-6b": {
        "device": "cuda",
    },
    "Qwen1.5-0.5B-Chat": {
        "device": "cuda",
    },`
改为：
`    "chatglm3-6b": {
        "device": "mps",
    },
    "Qwen1.5-0.5B-Chat": {
        "device": "mps",
    },`

**Comment by hushanhsiang** [comment]
我也遇到了，因為 Pytorch 沒安裝連結 Cuda 的套件~ 到下面連結 選取自己的安裝環境即可~

[https://pytorch.org/get-started/locally/](url)

**Comment by qiuyaofan** [comment]
https://blog.csdn.net/weixin_46333910/article/details/136242694
I fix this issue with 
```
conda create -n torch-gpu python=3.8

conda install pytorch::pytorch torchvision torchaudio -c pytorch
```
