### ISSUE TITLE
[BUG] 启动时报错：CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by cjrzs** [chatchat-space/Langchain-Chatchat#3813]
**问题描述 / Problem Description**
```
2024-04-19 15:07:28 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-04-19 15:07:28 | ERROR | stderr | Traceback (most recent call last):
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
2024-04-19 15:07:28 | ERROR | stderr |     self.run()
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/multiprocessing/process.py", line 108, in run
2024-04-19 15:07:28 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-04-19 15:07:28 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-04-19 15:07:28 | ERROR | stderr |     worker = ModelWorker(
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-04-19 15:07:28 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-04-19 15:07:28 | ERROR | stderr |     model.to(device)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1896, in to
2024-04-19 15:07:28 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
2024-04-19 15:07:28 | ERROR | stderr |     return self._apply(convert)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
2024-04-19 15:07:28 | ERROR | stderr |     module._apply(fn)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
2024-04-19 15:07:28 | ERROR | stderr |     module._apply(fn)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
2024-04-19 15:07:28 | ERROR | stderr |     module._apply(fn)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
2024-04-19 15:07:28 | ERROR | stderr |     param_applied = fn(param)
2024-04-19 15:07:28 | ERROR | stderr |   File "/home/bestseller/miniconda3/envs/langchain-cc-torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
2024-04-19 15:07:28 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-04-19 15:07:28 | ERROR | stderr | RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
2024-04-19 15:07:28 | ERROR | stderr | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
2024-04-19 15:07:28 | ERROR | stderr | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**复现问题的步骤 / Steps to Reproduce**
执行启动命令：`python startup.py -a`

**环境信息 / Environment Information**
```
操作系统：Linux-5.4.0-174-generic-x86_64-with-glibc2.17.
python版本：3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.1.16. fastchat版本：0.2.35
当前的PyTorch版本是：1.12.1+cu113
当前的torch是否能用CUDA：True
GPU数量： 1
GPU 名字:  GRID RTX8000P-24Q
当前gpu索引： 0
GPU 0: b'GRID RTX8000P-24Q'
Driver Version: b'450.119.03'
Total Memory: 24576.0 MB
Used Memory: 3248.20703125 MB
GPU Utilization: 0%
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/bestseller/models/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
```

**Comment by xdfnet** [comment]
提示错误信息 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

说明你没有安装CUDA环境或者你安装的PyTorch版本不支持CUDA，解决方法：
pip uninstall torch torchvision torchaudio

通过上面的命令进行卸载后重新安装官方给出的正确版本，安装命令如下：
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

**Comment by cjrzs** [comment]
重新安装了显卡驱动解决了该问题，但是在几轮问答之后，又会出现这个问题，很奇怪，明明显存还有很多富余。
